from sator.core.use_cases.resolution.references.patch import PatchReferencesResolution
from sator.core.use_cases.resolution.references.product import ProductReferencesResolution
from sator.core.use_cases.resolution.references.vulnerability import VulnerabilityReferencesResolution
